# Generated by Django 3.2.4 on 2021-09-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_topic', models.CharField(max_length=64, verbose_name='聊天话题')),
                ('mail_title', models.CharField(max_length=64, verbose_name='邮件标题')),
                ('date', models.DateField(verbose_name='聊天日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天记录基本信息',
                'verbose_name_plural': '聊天记录基本信息',
                'db_table': 'note_header',
            },
        ),
        migrations.CreateModel(
            name='note_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='聊天时间')),
                ('chater', models.CharField(max_length=32, verbose_name='说话人')),
                ('chat_content', models.TextField(verbose_name='聊天内容')),
                ('e_note_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end_wxnote.note_header')),
            ],
            options={
                'verbose_name': '聊天内容列表',
                'verbose_name_plural': '聊天内容列表',
                'db_table': 'note_list',
            },
        ),
    ]
